version: "3.8"

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - type: volume
              source: mongodb_data_volume
              target: /data/db
        env_file: ./.env

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        env_file: ./.env

volumes:
    mongodb_data_volume:
        external: False
